### PR TITLE
Use strict analysis modes instead of deprecated 'strong-mode' options

### PR DESCRIPTION
**Pull request by srawlins**
See https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks for more info.

### CODE REVIEW

**Review by DanTup — APPROVED** [review]
Thanks!

**Comment by DanTup** [comment]
Does this need updating in https://github.com/flutter/tests/blob/main/registry/DanTup_tiler.test? (I presume so if it's blocking something)

**Comment by srawlins** [comment]
Oh gosh, I guess so? I need to update the commit SHA? Yes this issue was blocking something.

**Comment by DanTup** [comment]
Yep, the hash at https://github.com/flutter/tests/blob/25de40a73c21ac52dc8c1756bb1e033b0be81227/registry/DanTup_tiler.test#L9 should be updated to 570364385b43c84b20a1d46b87344f3c9ae08aab if this change is needed for the Flutter customer tests to pass. It uses specific hashes (presumably to get consistent and not-flaky results as those repos are being pushed to).

**Comment by srawlins** [comment]
Thanks much! I'll update all the ones I'm touching in one batch. See https://github.com/dart-lang/sdk/issues/50751

**Pull request merged**
