### PR TITLE
Add a temporary migration flag

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
Hi @DanTup I'd like to migrate the tests so I could disable a rounding hack in flutter. Once the migration is done I'll open another PR to undo the code change.

This is going to affect text/isometric golden images ([example test failure in the flutter/flutter repo](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8773270557911220273/+/u/Customer_testing/customer_testing/test_stdout)). Is there a good way to extract the update golden images from github actions?

### CODE REVIEW

**Comment by DanTup** [comment]
>  Is there a good way to extract the update golden images from github actions?

I thought I had done this, but I can't find any evidence of it now. I currently just use my PC + MacBook to re-generate them. I can do this if required (or if it would save much future pain, I could look at making GH actions record them, it's probably not much work).

**Comment by DanTup** [comment]
> I thought I had done this

Yes, I had - they just only show up on failures. This PR ran and you can see the "Artifacts" section at the bottom of https://github.com/DanTup/tiler/actions/runs/5811820512 which zip files of the failures/updated files.

**Comment by LongCatIsLooong** [comment]
What would be the best way to update the golden images? Create a PR in https://github.com/DanTup/tiler-test-maps to update the golden images, and then update the sha1 of the submodule in this pull request?

**Comment by LongCatIsLooong** [comment]
Created https://github.com/DanTup/tiler-test-maps/pull/5

I don't have an arm mac so I just renamed the x86 golden hopefully that works.

**Comment by DanTup** [comment]
> What would be the best way to update the golden images? Create a PR in https://github.com/DanTup/tiler-test-maps to update the golden images, and then update the sha1 of the submodule in this pull request?

Yep!

> I don't have an arm mac so I just renamed the x86 golden hopefully that works.

If not, I can regenerate them here, I have one.

**Comment by DanTup** [comment]
The golden change was merged as https://github.com/DanTup/tiler-test-maps/commit/2558beeb380e9678b0b02870f696082f8c8dd175

**Comment by LongCatIsLooong** [comment]
Updated the submodule. Thank you for your help!

**Comment by DanTup** [comment]
@LongCatIsLooong merged this as 1c35701d0289abb8318f8f1ba0522d24e26b7f57. You should be able to update the flutter/tests repo with that hash to switch to this version.

**Comment by DanTup** [comment]
Oh - something that just occurred to me is that green here doesn't necessarily mean green for flutter/tests, because I think GH and flutter/tests might run opposite Mac architectures. I'll grab this on my M1 Mac shortly and verify if there's a difference (there definitely has been in the past, which is why I split them up).

**Comment by DanTup** [comment]
I just ran this on my M1 Mac and it doesn't seem like it produced any difference in what's already committed. So if you copied the x86 one, maybe there's not currently any difference between them 🤷‍♂️

(it's also possible I didn't do something correctly though... let me know if you see failures)

**Pull request merged**
